### ISSUE TITLE
[マジックドレッサーインベントリ] トランジション効果と同時にシェイプキーを変更する場合、トランジションが終わらないと変更されない

### ISSUE THREAD

**Issue by Narazaka** [HhotateA/AvatarModifyTools#16]
以下のように先に（干渉防止用）シェイプキーを変更してから靴下をフェードで消すなどをしたい事例において、シェイプキー操作オブジェクト側の設定にかかわらずフェードが終わらないとシェイプキーの変更が適用されない挙動になっていると思います。

![image](https://user-images.githubusercontent.com/1712548/131242081-fed47056-b1f0-4492-8a36-35bc0a205c8c.png)
![image](https://user-images.githubusercontent.com/1712548/131242089-fefce881-0b54-4308-ba12-21d02c77b965.png)

トランジションと同時にシェイプキーを操作するのは保証外かも知れませんが、シェイプキーにもdelayとdurationを適用すると適用範囲が広がるのではないかと思います。

**Comment by HhotateA** [comment]
報告ありがとうございます。対応しました<(_ _)>
