### ISSUE TITLE
現在のアニメーションの遷移だと空のState(Default)があるので挙動が不安定&Idleで止まるのでコンフリクトする

### ISSUE THREAD

**Issue by Neutrino-Gamma** [HhotateA/AvatarModifyTools#18]
はい、GitHubでもニュートリノγ(@kamiokande_d)でございます

このライブラリめちゃくちゃ便利ですね。。
なんか上手く動かなかったので、Issue投げさせていただきます

問題点
・motion未設定のStateは動作が不安定になる
・同じアイテムを複数のインベントリで操作する場合にInactiveIdolで止まるので現在の構成ではコンフリクトして動かなくなった

変更後
・Defaultに空のアニメーションを設定
  →asset内に空アニメーション作るようにしました

・ActiveIdleとInActiveIdleが必要ない気がするので削除
 →ActiveからInactiveにパラメータで遷移するように組み替えてます、で、InActiveしたらExitしてDefaultに戻る動きです

一応VRC内で動作確認して綺麗に動くのは見ましたが、Idleが必要だったなら後学のために教えてください。

プルリクエストのお作法がわからないのでzipで改修した奴だけ渡します。

[MagicalDresserInventorySetup.zip](https://github.com/HhotateA/AvatarModifyTools/files/7076832/MagicalDresserInventorySetup.zip)

**Comment by Neutrino-Gamma** [comment]
> はい、GitHubでもニュートリノγ(@kamiokande_d)でございます
> 
> このライブラリめちゃくちゃ便利ですね。。
> なんか上手く動かなかったので、Issue投げさせていただきます
> 
> 問題点
> ・motion未設定のStateは動作が不安定になる
> ・同じアイテムを複数のインベントリで操作する場合にInactiveIdolで止まるので現在の構成ではコンフリクトして動かなくなった
> 
> 変更後
> ・Defaultに空のアニメーションを設定
> →asset内に空アニメーション作るようにしました
> 
> ・ActiveIdleとInActiveIdleが必要ない気がするので削除
> →ActiveからInactiveにパラメータで遷移するように組み替えてます、で、InActiveしたらExitしてDefaultに戻る動きです
> 
> 一応VRC内で動作確認して綺麗に動くのは見ましたが、Idleが必要だったなら後学のために教えてください。
> 
> プルリクエストのお作法がわからないのでzipで改修した奴だけ渡します。
> 
> [MagicalDresserInventorySetup.zip](https://github.com/HhotateA/AvatarModifyTools/files/7076832/MagicalDresserInventorySetup.zip)

同期系に問題があったのでInactiveは見直し

**Comment by HhotateA** [comment]
IdleでオーバーライドしてるのはVRChatの仕様上，視界外でのAnimationが途中で止まってしまいActiveAnimationを通らずにIdleに行ってしまうことがあるためです．
遷移を始めながらワープする等で再現し，こちらの動画では遷移途中の中途半端な状態で服が固定されてしまっています．
https://gyazo.com/f45a042a427546b941c5891a081c9a53

**Comment by HhotateA** [comment]
Default内に空Animation作る修正しておきます！報告ありがとうございます。<(_ _)>

**Comment by Neutrino-Gamma** [comment]
そうですねぇ、なんかうまい手が無いか考え中です。
