### ISSUE TITLE
[マジックドレッサーインベントリ]設定ファイル開いてるときは保存先をファイルの位置にしてほしい

### ISSUE THREAD

**Issue by Neutrino-Gamma** [HhotateA/AvatarModifyTools#19]
すごい地味ですが、保存されてる設定ファイルを開いてる場合は
大抵は上書き保存をしたいと思うので保存先選択の開始位置を開いてる設定ファイルの位置にしてあげるといいかもしれません

**Comment by HhotateA** [comment]
報告ありがとうございます。対応しました<(_ _)>
