### ISSUE TITLE
[マジックドレッサーインベントリ] "VRChat Not Recommended"の中身の解説が欲しい

### ISSUE THREAD

**Issue by Narazaka** [HhotateA/AvatarModifyTools#26]
write defaultsはいいとして、Auto Next Pageがオフでもnext pageボタンが出来たりしてよく分からなかったので、このあたりの簡易的な説明が欲しいです。（write defaultはさておきほかは"VRChat Not Recommended"でもないような？）
![image](https://user-images.githubusercontent.com/1712548/131632199-2ca7abaa-4437-4844-a46f-8f0295bdebc9.png)

**Comment by HhotateA** [comment]
半分デバッグ用になってました，ｷﾞｸﾘ＞＜

どの項目を残すかも含めて検討します．
取り急ぎ
writeDefault : writeDefaultを上書きする
overrideNullAnimation : null登録のmotionを上書きする（挙動が安定するらしい）
duplicateSDKAssets : avatarにanimatorが登録されてない場合にSDKからコピーする
renameParameters : parameterから2バイト文字を除去する
modifyOriginalAsset : コピー元のアセットを上書きする （ #17  対策）
overrideSettings : Revertを行ってから変更を開始する
autoNextPage : menuにnextpageを自動追加する

**Comment by HhotateA** [comment]
解決済みかと思いますのでcloseします．
