### ISSUE TITLE
[にゃんにゃんメッシュエディター] モデルに元から設定された特定のシェイプキーが編集時におかしくなる

### ISSUE THREAD

**Issue by Narazaka** [HhotateA/AvatarModifyTools#42]
バージョン: fullpackageのv1.29.1およびv1.30.0

販売モデルをblender 2.79で改変して以下のような非公式な胸サイズシェイプキーを作成した下記のようなモデルについて

![image](https://user-images.githubusercontent.com/1712548/133790671-b4d8c47c-b172-4f42-aa80-8256c9aa4bf5.png)
![image](https://user-images.githubusercontent.com/1712548/133790697-7a4315ad-77c9-4848-9593-dbd3a071ebd1.png)
![image](https://user-images.githubusercontent.com/1712548/133791134-93fa2323-d816-43a2-8c27-b436703f2d9d.png)

（上記差分は「胸」シェイプキーによるもので、「胸2」もほぼ同様の部分をより膨らませるものになっています。そちらでも現象は同じです。）

「にゃんにゃんメッシュエディター」でアバターをセットし「Setup」を押してから当該メッシュ「身体_body」ボタンを押下した時点でこの「胸」および「胸2」シェイプキーが不自然に変形したような挙動になります。

![image](https://user-images.githubusercontent.com/1712548/133791675-12417a99-6153-43df-a1c9-de62053a5408.png)

「胸=0」で「Setup」してから「身体_body」ボタンを押下し、
![image](https://user-images.githubusercontent.com/1712548/133792601-429f8292-bd2b-4535-914f-8e45809a6ae0.png)
そこから「胸=100」にした場合
![image](https://user-images.githubusercontent.com/1712548/133790870-4f51b0a9-e03f-4788-88db-8b4b4cc383b8.png)

「胸=100」で「Setup」してから「身体_body」ボタンを押下し、
![image](https://user-images.githubusercontent.com/1712548/133792232-fcaac742-f6f5-4081-b7c0-0cb4a7eb0f7a.png)
そこから「胸=0」にした場合
![image](https://user-images.githubusercontent.com/1712548/133790771-2a04e16d-3fff-4ff5-aef8-050a8bd9e816.png)

「Setup」時点でのシェイプキー状況によってこれらは再現可能でした。

これらを「Save」すると実際にこの変形状態になったメッシュになります。ウインドウを閉じると元に戻ります。
これら自分で足した「胸」「胸2」以外の元モデルにあった「干渉防止_*」系のシェイプキーは正常に動作していました。

このメッシュがあるfbxは下記のようなインポート設定です。
![image](https://user-images.githubusercontent.com/1712548/133794209-e22f383b-1538-4f26-95f3-f97e3fc4799d.png)
ためしに下記のように設定しても事象は変化しませんでした。
![image](https://user-images.githubusercontent.com/1712548/133794613-2fd5d0ce-8753-42cb-99b0-43e9829e904a.png)

ちょっと条件が不明なため再現可能なメッシュ等は出せません。すみません。
（これらは https://narazaka.booth.pm/items/1853565 の「シンシアちゃんサイズ改変データ.zip」に準ずる物なのでもしシンシアちゃんをお持ちなら再現可能かも知れません）

**Comment by Narazaka** [comment]
1.30.4でためしたらシェイプキーの挙動自体は直った感じがありますが、かわりにこうなりました
![image](https://user-images.githubusercontent.com/1712548/133931975-4eda2713-f7e1-4033-9577-4151f0dd805b.png)

**Comment by HhotateA** [comment]
修正できたかもなので試してみてください<(_ _)>
https://github.com/HhotateA/AvatarModifyTools/releases/tag/dev1.30.14

**Comment by Narazaka** [comment]
当該モデルで正常動作しているように見えます。
ありがとうございました！

**Comment by HhotateA** [comment]
修正済み
