### ISSUE TITLE
マテリアル結合＆テクスチャのアトラス化が失敗する

### ISSUE THREAD

**Issue by dreamdrive** [HhotateA/AvatarModifyTools#57]
素晴らしいツールをありがとうございます。
にゃんにゃんメッシュエディターにて、conbine Materials「By Shader」で、マテリアル（７つ）を結合するオプションにチェックを入れたのですが、UVの並びとテクスチャの並びが一致してないようで、テクスチャが入れ替わった感じになって壊れてしまいます。

![image](https://user-images.githubusercontent.com/9768620/138579159-79c72be8-895d-463c-a5c4-b94bb5f2aab4.png)
実行すると、確かにマテリアルは１つになっていますが・・・
![image](https://user-images.githubusercontent.com/9768620/138579154-8db5601e-4e77-4601-991a-c9e396702190.png)

ちなみに、Quest対応に使用したかったため、デシメートもかけています。

**Comment by dreamdrive** [comment]
お騒がせしました。原因分かりました。
Quest対応する前に、cluster対応させようと思って、シェーダーを/VRM/Mtoonに変更した状態で作業していたのですが、そのせいでした。
にゃんにゃんメッシュエディターで出力したあと、統合されたマテリアルのシェーダー内で、Shade Colorに設定されたテクスチャが、統合前のものからは自動で変更されていなかったため、表示が崩れてしまうようです。
UV自体はちゃんとできていましたので、順番が入れ替わっているようなことはありませんでした。
Shade Colorにも統合後のテクスチャを挿入すれば問題ありませんでした。

![image](https://user-images.githubusercontent.com/9768620/138593973-b0f3d51a-35b7-4d09-ad92-e367bc7938d8.png)

一応、自己完結しましたが、シェーダーによっては同じことが起こるかと思いますので、残しておきます。

**Comment by HhotateA** [comment]
報告有難うございます．
現状Unlit意外だと結構不安定なの明記した方がいいかもですね．

**Comment by dreamdrive** [comment]
そうですね。いったんUnlitに変更してから、各シェーダーで設定し直すみたいな手順を書いてもらったらトラブル少ないかもしれませんね。
