### ISSUE TITLE
[EmoteMotionKit] SetupとSave/Load Settingsとで拡張子が異なる

### ISSUE THREAD

**Issue by lindwurm** [HhotateA/AvatarModifyTools#61]
v1.30.19 時点で

| ボタン | 拡張子 |
|:---:|:---|
| Setup | `*.asset` |
| Save Settings | `*.emotemotion.asset` |
| Load Settings | `*.emotemotion.asset` |

となっています。

Setup で出力される `*.asset` もダブルクリックすれば設定を復元できており、大きな問題ではないのですが、マジックドレッサーインベントリでは揃えてあるようなので少し気になりました。何らかの意図があったらすみません。

**Comment by HhotateA** [comment]
次回アップデートで修正します．報告ありがとうございました<(_ _)>
